jobs:
  Job1:
    name: Job 11
    steps:
      - type: script
        script-content: echo 'hello'
  mixedTests:
    name: Job 22
    dependencies:
      - Job1
    steps:
      - type: script
        script-content: echo 'hello'
  CUSTOM_NAME:
    name: Job 33
    dependencies:
      - Job2
    steps:
      - type: script
        script-content: echo 'hello'
